# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 195595e1f6991fb830ba0512d4ca8a9666f34641905abc61d32530826e7a6fa1939675cd6cca832baef528fb37f8ef8897d9991c9e88abeea321ca5529497ea7

test:
  secret_key_base: 22068e4bed0c53cb9691e1f05ef0e20f3fd07017f5e013556208209333246568a62426613337dc7b593e9f74cf48303fd50646e68e28ea96051d70bddcb94e59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
